# release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🚀 New features
      labels:
        - 'type: feature'
    - title: 🐛 Bug Fixes
      labels:
        - 'type: bug'
    - title: 🧰 Maintenance
      labels:
        - 'type: maintenance'
    - title: 📦 Dependency Updates
      labels:
        - 'type: dependencies'
    - title: 📖 Documentation
      labels:
        - 'type: docs'

    - title: Other Changes
      labels:
        - '*'
